// <auto-generated />
using System;
using API_Net_Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Net_Core.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("API_Net_Core.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "teste123@.com",
                            Nome = "Adam1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "teste123@.com",
                            Nome = "Adam2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "teste123@.com",
                            Nome = "Adam3"
                        });
                });

            modelBuilder.Entity("API_Net_Core.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descr")
                        .HasColumnType("longtext");

                    b.Property<int?>("pessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("pessoaId");

                    b.ToTable("Tarefa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descr = "teste"
                        },
                        new
                        {
                            Id = 2,
                            Descr = "teste2"
                        },
                        new
                        {
                            Id = 3,
                            Descr = "teste3"
                        });
                });

            modelBuilder.Entity("API_Net_Core.Tarefa", b =>
                {
                    b.HasOne("API_Net_Core.Pessoa", "pessoa")
                        .WithMany("Tarefas")
                        .HasForeignKey("pessoaId");

                    b.Navigation("pessoa");
                });

            modelBuilder.Entity("API_Net_Core.Pessoa", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
